//! Domain types for the Rules Engine (R-03).
//!
//! Provides JSON-serializable rule definitions with support for both structural
//! (field-matching) and semantic (vector-similarity) conditions.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// A user-defined email automation rule persisted in SQLite.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Rule {
    pub id: String,
    pub name: String,
    #[serde(default)]
    pub description: String,
    pub conditions: Vec<RuleCondition>,
    pub actions: Vec<RuleAction>,
    #[serde(default)]
    pub priority: i32,
    #[serde(default = "default_enabled")]
    pub enabled: bool,
    #[serde(default = "Utc::now")]
    pub created_at: DateTime<Utc>,
    #[serde(default = "Utc::now")]
    pub updated_at: DateTime<Utc>,
}

fn default_enabled() -> bool {
    true
}

/// Conditions that determine whether a rule matches an email.
///
/// Supports structural field matching, semantic vector similarity,
/// and boolean combinators (And, Or, Not).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum RuleCondition {
    /// Match a specific email field against a value.
    FieldMatch {
        field: EmailField,
        operator: MatchOperator,
        value: String,
    },
    /// Semantic similarity search (unique to Emailibrium).
    ///
    /// The `query` is embedded into a vector and compared against the email's
    /// vector representation. Matches when cosine similarity >= `threshold`.
    Semantic {
        query: String,
        #[serde(default = "default_threshold")]
        threshold: f32,
    },
    /// All sub-conditions must match.
    And { conditions: Vec<RuleCondition> },
    /// At least one sub-condition must match.
    Or { conditions: Vec<RuleCondition> },
    /// The sub-condition must NOT match.
    Not { condition: Box<RuleCondition> },
}

fn default_threshold() -> f32 {
    0.75
}

/// Email fields available for condition matching.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum EmailField {
    From,
    To,
    Subject,
    Body,
    Labels,
    Date,
}

impl EmailField {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::From => "from",
            Self::To => "to",
            Self::Subject => "subject",
            Self::Body => "body",
            Self::Labels => "labels",
            Self::Date => "date",
        }
    }
}

impl std::fmt::Display for EmailField {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Comparison operators for field-match conditions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum MatchOperator {
    Contains,
    Equals,
    StartsWith,
    EndsWith,
    Regex,
    GreaterThan,
    LessThan,
}

impl MatchOperator {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Contains => "contains",
            Self::Equals => "equals",
            Self::StartsWith => "startsWith",
            Self::EndsWith => "endsWith",
            Self::Regex => "regex",
            Self::GreaterThan => "greaterThan",
            Self::LessThan => "lessThan",
        }
    }
}

/// Actions that can be applied to emails when a rule matches.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "camelCase")]
pub enum RuleAction {
    AddLabel { label: String },
    RemoveLabel { label: String },
    Archive,
    Delete,
    Forward { to: String },
    MarkRead,
    MarkImportant,
}

impl RuleAction {
    /// Human-readable label for the action type.
    pub fn action_type(&self) -> &'static str {
        match self {
            Self::AddLabel { .. } => "addLabel",
            Self::RemoveLabel { .. } => "removeLabel",
            Self::Archive => "archive",
            Self::Delete => "delete",
            Self::Forward { .. } => "forward",
            Self::MarkRead => "markRead",
            Self::MarkImportant => "markImportant",
        }
    }
}

/// A pending action generated by the processor but not yet executed.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PendingAction {
    pub email_id: String,
    pub rule_id: String,
    pub rule_name: String,
    pub action: RuleAction,
}

// ---------------------------------------------------------------------------
// EvaluateOnly mode (DDD-007 addendum, ADR-030 Phase A)
// ---------------------------------------------------------------------------

/// How a rule should be processed.
///
/// `Apply` is the existing default and emits commands to the Email Operations
/// context. `EvaluateOnly` (new for ADR-030) returns the same matched set
/// without emitting any commands or touching providers; PlanBuilder uses it
/// to produce predicate rows for the cleanup plan.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum RuleExecutionMode {
    Apply,
    EvaluateOnly,
}

/// How a matched email was determined to match a rule. Carried through to
/// the UI on plan rows so users can see *why* a row exists.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum RuleMatchBasis {
    /// All conditions are field-match / structural.
    Literal,
    /// At least one condition is semantic / vector-similarity.
    Semantic,
    /// Mixed structural + semantic conditions.
    Hybrid,
}

/// Scope for `evaluate_rules` in EvaluateOnly mode. Phase A defines a minimal
/// shape (per-account); Phase C may extend with date filters or label filters.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EvaluationScope {
    pub account_id: String,
    /// If empty, evaluates against all enabled rules. Otherwise only the listed rule IDs.
    #[serde(default)]
    pub rule_ids: Vec<String>,
    /// Maximum number of `matched_email_ids` to return per rule (for UI preview).
    /// Capped at 20. Default 20.
    #[serde(default = "default_sample_size")]
    pub sample_size: u32,
}

fn default_sample_size() -> u32 {
    20
}

/// A non-mutating evaluation of one rule against the local email repository.
///
/// Produced by `evaluate_rules` in `EvaluateOnly` mode. The plan builder lifts
/// each `RuleEvaluation` into a `PlannedOperationPredicate`. Determinism of
/// `matched_email_ids` (head 5 / tail 5 / 10 stratified by date, capped at 20)
/// is required for `plan_hash` stability.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuleEvaluation {
    pub rule_id: String,
    /// Bounded sample (≤ 20) of matched email ids. See `evaluate_rules`.
    pub matched_email_ids: Vec<String>,
    /// Total estimated count of all matches (not truncated).
    pub projected_count: u64,
    /// Actions the rule would have applied if `Apply` mode had been used.
    pub intended_actions: Vec<RuleAction>,
    pub match_basis: RuleMatchBasis,
}

impl RuleEvaluation {
    /// Helper: classify a rule's conditions into a single `RuleMatchBasis`.
    pub fn basis_for(conditions: &[RuleCondition]) -> RuleMatchBasis {
        let mut has_semantic = false;
        let mut has_literal = false;
        for c in conditions {
            Self::scan(c, &mut has_semantic, &mut has_literal);
        }
        match (has_semantic, has_literal) {
            (true, true) => RuleMatchBasis::Hybrid,
            (true, false) => RuleMatchBasis::Semantic,
            _ => RuleMatchBasis::Literal,
        }
    }

    fn scan(c: &RuleCondition, has_semantic: &mut bool, has_literal: &mut bool) {
        match c {
            RuleCondition::Semantic { .. } => *has_semantic = true,
            RuleCondition::FieldMatch { .. } => *has_literal = true,
            RuleCondition::And { conditions } | RuleCondition::Or { conditions } => {
                for c2 in conditions {
                    Self::scan(c2, has_semantic, has_literal);
                }
            }
            RuleCondition::Not { condition } => Self::scan(condition, has_semantic, has_literal),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rule_condition_field_match_roundtrip() {
        let cond = RuleCondition::FieldMatch {
            field: EmailField::Subject,
            operator: MatchOperator::Contains,
            value: "urgent".to_string(),
        };
        let json = serde_json::to_string(&cond).unwrap();
        let parsed: RuleCondition = serde_json::from_str(&json).unwrap();
        assert_eq!(cond, parsed);
    }

    #[test]
    fn rule_condition_semantic_roundtrip() {
        let cond = RuleCondition::Semantic {
            query: "project updates".to_string(),
            threshold: 0.8,
        };
        let json = serde_json::to_string(&cond).unwrap();
        let parsed: RuleCondition = serde_json::from_str(&json).unwrap();
        assert_eq!(cond, parsed);
    }

    #[test]
    fn rule_condition_nested_roundtrip() {
        let cond = RuleCondition::And {
            conditions: vec![
                RuleCondition::FieldMatch {
                    field: EmailField::From,
                    operator: MatchOperator::Contains,
                    value: "boss@co.com".to_string(),
                },
                RuleCondition::Not {
                    condition: Box::new(RuleCondition::FieldMatch {
                        field: EmailField::Labels,
                        operator: MatchOperator::Contains,
                        value: "processed".to_string(),
                    }),
                },
            ],
        };
        let json = serde_json::to_string(&cond).unwrap();
        let parsed: RuleCondition = serde_json::from_str(&json).unwrap();
        assert_eq!(cond, parsed);
    }

    #[test]
    fn rule_action_roundtrip() {
        let actions = vec![
            RuleAction::AddLabel {
                label: "work".to_string(),
            },
            RuleAction::Archive,
            RuleAction::Forward {
                to: "team@co.com".to_string(),
            },
        ];
        for action in &actions {
            let json = serde_json::to_string(action).unwrap();
            let parsed: RuleAction = serde_json::from_str(&json).unwrap();
            assert_eq!(action, &parsed);
        }
    }

    #[test]
    fn full_rule_roundtrip() {
        let rule = Rule {
            id: "r-1".to_string(),
            name: "Test Rule".to_string(),
            description: "A test".to_string(),
            conditions: vec![RuleCondition::FieldMatch {
                field: EmailField::Subject,
                operator: MatchOperator::Contains,
                value: "hello".to_string(),
            }],
            actions: vec![RuleAction::MarkRead],
            priority: 10,
            enabled: true,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let json = serde_json::to_string(&rule).unwrap();
        let parsed: Rule = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.id, rule.id);
        assert_eq!(parsed.name, rule.name);
    }

    #[test]
    fn email_field_display() {
        assert_eq!(EmailField::From.as_str(), "from");
        assert_eq!(EmailField::Labels.as_str(), "labels");
    }

    #[test]
    fn default_threshold_is_075() {
        let json = r#"{"type":"semantic","query":"test"}"#;
        let cond: RuleCondition = serde_json::from_str(json).unwrap();
        if let RuleCondition::Semantic { threshold, .. } = cond {
            assert!((threshold - 0.75).abs() < f32::EPSILON);
        } else {
            panic!("Expected Semantic condition");
        }
    }
}
