#!/usr/bin/env bash
set -euo pipefail

# ============================================================================
# Emailibrium — AI Provider Configuration
# ============================================================================
# Configures ONNX (local default), Ollama (local), and cloud AI providers.
# Writes API keys to .env.local (gitignored).
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env.local"

# Colors
BOLD=$(tput bold 2>/dev/null || echo '')
GREEN=$(tput setaf 2 2>/dev/null || echo '')
YELLOW=$(tput setaf 3 2>/dev/null || echo '')
BLUE=$(tput setaf 4 2>/dev/null || echo '')
RED=$(tput setaf 1 2>/dev/null || echo '')
RESET=$(tput sgr0 2>/dev/null || echo '')

# Load existing .env.local if present
declare -A ENV_VARS
if [[ -f "$ENV_FILE" ]]; then
  while IFS='=' read -r key val; do
    # Skip comments and empty lines
    [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
    ENV_VARS["$key"]="$val"
  done < "$ENV_FILE"
fi

env_is_set() {
  local key="$1"
  [[ -n "${ENV_VARS[$key]:-}" ]] || [[ -n "${!key:-}" ]]
}

write_env() {
  local key="$1"
  local val="$2"
  ENV_VARS["$key"]="$val"
}

flush_env() {
  {
    echo "# Emailibrium — Local environment overrides"
    echo "# Generated by scripts/setup-ai.sh"
    echo "# This file is gitignored. Never commit API keys."
    echo ""
    for key in $(echo "${!ENV_VARS[@]}" | tr ' ' '\n' | sort); do
      echo "${key}=${ENV_VARS[$key]}"
    done
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
}

echo "${BOLD}Configuring AI providers...${RESET}"
echo ""

# ─── Step 1: ONNX (default, local) ──────────────────────────────────────────

echo "${BOLD}${BLUE}Step 1: ONNX Runtime (default embedding provider)${RESET}"
echo "  ONNX runs fully offline — no API key needed."
echo "  Models are downloaded once to backend/.fastembed_cache/"
echo ""

if [[ -d "$PROJECT_ROOT/backend/.fastembed_cache" ]]; then
  echo "  ${GREEN}[cached]${RESET}  ONNX model cache found"
else
  echo "  ${YELLOW}[not cached]${RESET} Models will download on first backend start"
fi

echo ""
read -rp "  Download ONNX models now? (requires built backend) [y/N]: " onnx_choice
if [[ "${onnx_choice,,}" == "y" ]]; then
  if [[ -f "$PROJECT_ROOT/backend/target/release/emailibrium" ]]; then
    echo "  Downloading models..."
    (cd "$PROJECT_ROOT/backend" && ./target/release/emailibrium --download-models) || {
      echo "  ${YELLOW}Download failed. Models will download on first run.${RESET}"
    }
  elif [[ -f "$PROJECT_ROOT/backend/target/debug/emailibrium" ]]; then
    echo "  Downloading models (debug build)..."
    (cd "$PROJECT_ROOT/backend" && ./target/debug/emailibrium --download-models) || {
      echo "  ${YELLOW}Download failed. Models will download on first run.${RESET}"
    }
  else
    echo "  ${YELLOW}Backend not built yet. Run 'make -C backend build' first, then re-run this step.${RESET}"
  fi
fi

echo ""

# ─── Step 2: Built-in Local LLM (ADR-021) ──────────────────────────────────

echo "${BOLD}${BLUE}Step 2: Built-in Local LLM (default generative provider)${RESET}"
echo "  A small language model (~350 MB) runs locally for email classification."
echo "  No API key needed. No external service needed."
echo "  Default model: Qwen 2.5 0.5B (Q4_K_M quantization)"
echo ""

BUILTIN_CACHE="$HOME/.emailibrium/models/llm"
if [[ -d "$BUILTIN_CACHE" ]] && find "$BUILTIN_CACHE" -name "*.gguf" -print -quit 2>/dev/null | grep -q .; then
  echo "  ${GREEN}[cached]${RESET}  GGUF model found in $BUILTIN_CACHE"
else
  echo "  ${YELLOW}[not cached]${RESET} Model will download on first classification request (~350 MB)"
  echo ""
  read -rp "  Download the default model now? [Y/n]: " builtin_choice
  builtin_choice="${builtin_choice:-y}"
  if [[ "${builtin_choice,,}" == "y" ]]; then
    if command -v npx &>/dev/null; then
      echo "  Downloading qwen2.5-0.5b-q4km..."
      (cd "$PROJECT_ROOT" && npx tsx scripts/models.ts download --default) || {
        echo "  ${YELLOW}Download failed. Model will download on first use.${RESET}"
      }
    else
      echo "  ${YELLOW}npx not found. Model will download on first backend request.${RESET}"
    fi
  fi
fi

echo ""

# ─── Step 3: Ollama (local LLM) ─────────────────────────────────────────────

echo "${BOLD}${BLUE}Step 3: Ollama (local LLM, optional)${RESET}"
echo "  Ollama provides local LLM inference without cloud API keys."
echo ""

if command -v ollama &>/dev/null; then
  echo "  ${GREEN}[installed]${RESET} Ollama found"
  if ollama list &>/dev/null 2>&1; then
    echo "  ${GREEN}[running]${RESET}   Ollama is active"
    echo ""
    echo "  Currently pulled models:"
    ollama list 2>/dev/null | head -10 || true
    echo ""
    read -rp "  Pull recommended model (llama3.2)? [y/N]: " ollama_pull
    if [[ "${ollama_pull,,}" == "y" ]]; then
      ollama pull llama3.2 || echo "  ${YELLOW}Pull failed. Try manually: ollama pull llama3.2${RESET}"
    fi
  else
    echo "  ${YELLOW}[stopped]${RESET}  Ollama installed but not running"
    echo "           Start with: ollama serve"
  fi
else
  echo "  ${YELLOW}[not installed]${RESET} Ollama"
  echo "  Install: https://ollama.com/download"
fi

echo ""

# ─── Step 4: Cloud providers ────────────────────────────────────────────────

echo "${BOLD}${BLUE}Step 4: Cloud AI Providers (optional)${RESET}"
echo "  API keys are stored in .env.local (gitignored)."
echo "  Press Enter to skip any provider."
echo ""

# OpenAI
if env_is_set "EMAILIBRIUM_OPENAI_API_KEY"; then
  echo "  ${GREEN}[configured]${RESET} OpenAI"
else
  read -rp "  OpenAI API key (sk-...): " openai_key
  if [[ -n "$openai_key" ]]; then
    write_env "EMAILIBRIUM_OPENAI_API_KEY" "$openai_key"
    echo "  ${GREEN}[saved]${RESET}      OpenAI"
  else
    echo "  ${YELLOW}[skipped]${RESET}    OpenAI"
  fi
fi

# Anthropic
if env_is_set "EMAILIBRIUM_ANTHROPIC_API_KEY"; then
  echo "  ${GREEN}[configured]${RESET} Anthropic"
else
  read -rp "  Anthropic API key (sk-ant-...): " anthropic_key
  if [[ -n "$anthropic_key" ]]; then
    write_env "EMAILIBRIUM_ANTHROPIC_API_KEY" "$anthropic_key"
    echo "  ${GREEN}[saved]${RESET}      Anthropic"
  else
    echo "  ${YELLOW}[skipped]${RESET}    Anthropic"
  fi
fi

# Gemini
if env_is_set "EMAILIBRIUM_GEMINI_API_KEY"; then
  echo "  ${GREEN}[configured]${RESET} Gemini"
else
  read -rp "  Gemini API key: " gemini_key
  if [[ -n "$gemini_key" ]]; then
    write_env "EMAILIBRIUM_GEMINI_API_KEY" "$gemini_key"
    echo "  ${GREEN}[saved]${RESET}      Gemini"
  else
    echo "  ${YELLOW}[skipped]${RESET}    Gemini"
  fi
fi

# Cohere
if env_is_set "EMAILIBRIUM_COHERE_API_KEY"; then
  echo "  ${GREEN}[configured]${RESET} Cohere"
else
  read -rp "  Cohere API key: " cohere_key
  if [[ -n "$cohere_key" ]]; then
    write_env "EMAILIBRIUM_COHERE_API_KEY" "$cohere_key"
    echo "  ${GREEN}[saved]${RESET}      Cohere"
  else
    echo "  ${YELLOW}[skipped]${RESET}    Cohere"
  fi
fi

# Write .env.local if any keys were set
if [[ ${#ENV_VARS[@]} -gt 0 ]]; then
  flush_env
  echo ""
  echo "  ${GREEN}Saved to .env.local (chmod 600)${RESET}"
fi

echo ""
echo "────────────────────────────────────────"
echo "${BOLD}AI Provider Summary:${RESET}"
echo "  ${GREEN}ONNX${RESET}        Default embedding (always available, no key needed)"
if [[ -d "$BUILTIN_CACHE" ]] && find "$BUILTIN_CACHE" -name "*.gguf" -print -quit 2>/dev/null | grep -q .; then
  echo "  ${GREEN}Built-in${RESET}    Local LLM (model cached)"
else
  echo "  ${YELLOW}Built-in${RESET}    Local LLM (downloads on first use)"
fi
if command -v ollama &>/dev/null; then
  echo "  ${GREEN}Ollama${RESET}    Local LLM (installed)"
else
  echo "  ${YELLOW}Ollama${RESET}    Not installed"
fi
for provider in OpenAI Anthropic Gemini Cohere; do
  key_name="EMAILIBRIUM_${provider^^}_API_KEY"
  if env_is_set "$key_name"; then
    echo "  ${GREEN}$provider${RESET}  Configured"
  else
    echo "  ${YELLOW}$provider${RESET}  Not configured"
  fi
done
echo ""
echo "Tip: Set EMAILIBRIUM_GENERATIVE_PROVIDER=ollama|cloud in .env.local"
echo "     to override the default built-in LLM provider."
