// The root access token is only held by the caller long enough to exchange it
// for the engine's HttpOnly session cookie. Never put it in storage or a URL.
export async function getEngineSession(): Promise<boolean> {
  const response = await fetch('/api/v1/session', {
    credentials: 'same-origin',
    signal: AbortSignal.timeout(5000),
  });
  if (response.status === 401) return false;
  if (!response.ok)
    throw new Error('Cannot reach the local engine. Start it and retry the connection.');
  const data: { authenticated?: boolean } = await response.json();
  return data.authenticated === true;
}

export async function connectEngine(token: string): Promise<void> {
  const response = await fetch('/api/v1/session', {
    method: 'POST',
    credentials: 'same-origin',
    headers: { Authorization: `Bearer ${token.trim()}` },
    signal: AbortSignal.timeout(5000),
  });
  if (response.status === 401)
    throw new Error(
      'Access token was not accepted. Check the token generated by your local setup.',
    );
  if (!response.ok)
    throw new Error('Cannot reach the local engine. Start it and retry the connection.');
}

export async function lockEngine(): Promise<void> {
  const response = await fetch('/api/v1/session', {
    method: 'DELETE',
    credentials: 'same-origin',
    signal: AbortSignal.timeout(5000),
  });
  if (!response.ok && response.status !== 401)
    throw new Error(
      'Unable to revoke the engine session. Retry before leaving this browser unattended.',
    );
}
